apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
  name: mealie
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mealie
  template:
    metadata:
      labels:
        app: mealie
    spec:
      containers:
      - image: hkotel/mealie:v3.16.0
        name: mealie
        ports:
          - containerPort: 9000

        volumeMounts:
          - mountPath: /app/data/
            name: mealie-data

      restartPolicy: Always

      volumes:
        - name: mealie-data
          persistentVolumeClaim:
            claimName: mealie-data-pvc
