apiVersion: v1
kind: ConfigMap
metadata:
  name: audio-configmap
  namespace: audiobookshelf
spec:
  ports:
  - port: 3005
    protocol: TCP
    targetPort: 3005
  type: ClusterIP
data:
  TZ: Europe/London
