apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  namespace: audiobookshelf
resources:
  - namespace.yaml
  - storage.yaml
  - service.yaml
  - configmap.yaml
  - deployment.yaml
