apiVersion: v1
kind: Service
metadata:
  name: audiobookshelf
  namespace: audiobookshelf
spec:
  type: ClusterIP
  ports:
    - port: 3005
      protocol: TCP
      targetPort: 3005
  selector:
    app: audiobookshelf
