apiVersion: apps/v1
kind: Deployment
metadata:
  name: wallabag
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wallabag
  template:
    metadata:
      labels:
        app: wallabag
    spec:
      containers:
        - image: wallabag/wallabag:2.6.13
          name: wallabag
          ports: 
            - containerPort: 7676

          envFrom:
             - configMapRef:
                 name: wallabag-configmap
            #- secretRef:
            #    name: 

          #securityContext:
          #  fsGroup: 33
          #  runAsUser: 33
          #  runAsGroup: 33
          #  allowPrivilegeEscalation: false

          volumeMounts:
            - mountPath: /var/www/wallabag/data
              name: wallabag-data
            - mountPath: /var/www/wallabag/web/assets/images
              name: wallabag-images

      restartPolicy: Always

      volumes:
        - name: wallabag-data
          persistentVolumeClaim:
            claimName: wallabag-data-pvc
        - name: wallabag-images
          persistentVolumeClaim:
            claimName: wallabag-images-pvc
