apiVersion: v1
data:
    b514995b-d405-4a91-9cdf-48c84fcd482d.json: ENC[AES256_GCM,data:6dRyc2hD6ZDdG5I3XLFtwAQPHoaQT4V64QHGdPdFHYjHXJp8duqsYOXtAwm85nkbrihmPyPvyQsjVaVezKNR5bggwVY/VUxqjihY8GBOwlTV8OilPhlyhNnLjqUzODl1G0YjkaEsh39QlT73xiXfj1UKk8gCKUfjt1cM9GVLaPr3i+stt3yWR4agl7djk19jLxWE80UIZSHw8WQPDJhjszakHctKbfg5zlUSRjS5EqEQIGlWWuZ5BnsJdbRO6lT8VUs5tUoSJAsHS0jLdmYwkTyLWdA5GQ126IAAOOaR79oxDurB5m8r8P6BiRk=,iv:GR0B/UiHtNvBc7bnxAeWgbfrtTKc5YJ+L+zNThtyCE0=,tag:iEbd4DYnmPAxsZsEN7jPjg==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - recipient: age1u5lg9qlsue2ex0wc36gvpezn3az7gpszzkxwqjega082l7uzq9fsuc7f03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2c25YbHZacGJnWUw2QkJp
            bDk1YitZZFljVU9Uc1RVVlhsd00vV3VWS2o4CktacDFoWVd5VUNCNEtENUZtWlNY
            QjkwUVRKRWwwUCtELzZFYjB3Y2pLaG8KLS0tIFVveDluYWo5K0FiQjN1aTJQRHFa
            THhZN0hERXpFQjNHaDRIdXgvVGlGTFEKpcyl6xpwFvmSLquhkEajt2rokW7uQ2vs
            RhcYXNkVJDWPbg6pJGycub03RJLmz0K4kostjtOCk32uAGt8TN/Q4Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-18T11:20:55Z"
    mac: ENC[AES256_GCM,data:DCFMAmDLspMMEULlo8fzG8eNvYRo9ChQU/GI/X9f+RZesID0/LUACQI97QzH4UmOnmkjsrG/ZfZ43w+fdiimK1NoV++FG5O+aIpJVAARedzy7Oxv0q1T5my0d23o4lrlZjIufL58buNnSO59Vj+S3Ki4idQjPQNg8fkIl/IG6Nw=,iv:jtIXZhJ+1JsMtFfc8VUqC7cvFyfUwzwgO6vYQAKtgJg=,tag:fZyWmxwRZkyyHYPk+QIWFA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
