apiVersion: v1
data:
    d549264e-471a-4608-9426-20a83be52e85.json: ENC[AES256_GCM,data:jg9T1eMIaQsFOgkVS7sc81Tiv8ZImlbxHANeySAq9x7bc1n758gM1xHn3flUxvwULm5MvZNlIfW7pe3lop889XU/35+3UPGT7+rIbIARm2B4Tr/pHL1RmKf+5m0/ol17jb+yY2lXR8RMiDHBSAsR7k6vASU8AHS1mbTp8kJx4ymMXPiWrotNHTdKA/rls6YmTau1idGZFvIAlaAniGINAAhu43FtsX93Oy05F5G9XPF3+TOW0CQhms4UXb0jF4ucyoU0K0IEJXWGdh2l/qlSbZOy3C8uIug2yKDiuLkaL7pg/xHg0ZMXaIQxvEQ=,iv:Ul47WNQHFQIMLQaVAuEhTZLMu2hqgpztgfbpC8zzL6c=,tag:ShapqsW/er/5J50/iOS/QA==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - recipient: age1u5lg9qlsue2ex0wc36gvpezn3az7gpszzkxwqjega082l7uzq9fsuc7f03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4dWRDUXdOOXRzbHhsbFNM
            bWNaOFR0ZHo0V2FSczNNYldOUTNmSlFiZlJnCkl0UmlDVmprcTBxUEd0MzZ6UVo2
            ODhmclY0Snp6WTR4VVp1WmJZVWxhcUUKLS0tIGoyQU5zY01mRXRnMCtsVXNqc1pO
            d3U3OHNhaXFkQVhCMnliU3BhdytPRlkK6GuttUSisL3AIcKazemSIT6dYB23p4Sl
            /jYwy1Lt9sdh9OeWx08S+PZQ8m71ZqUwpG3j0fAf7dQxTo947yRJxQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-18T11:04:29Z"
    mac: ENC[AES256_GCM,data:5mlmOcDjYSKjsIZ845Oj07chynPGLn05bacbYVYhVwFf7w1/JYJLve7RmhTIJHOKlBw+G/A7M6DJNBAQrAnLqciQ4qiowxDKwMKxpM1TUkkG5MDMwkEVxQRNQ4PE+F3A9xCh+Qo10BJXPrGAY7SIHgc1GN/BuS041b/IdnDCGu8=,iv:w2lIwn/zSd4+dWh0/0RqBbrz+yE41nY9slcMbBjnqso=,tag:WtnwOF+QcnrfpOMY2w03zw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
