apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:6Zv16Pd8yqkSVN6oYXS6Kt8nmrxPgkRBmiVmefrQ6ENdrVNNZaTd72LAcJs1utL9FFgqbCeN274gmgr2ZrEdfx518A8KLhnmqThU+2E0Xnv7BpGE/LpmTj7HcnK6qwEiie0X0JAHtbjyyWdHDvUdwrJ86+Cuxsqs3TndDY1Zb2wEz1w8G9p1D+1Pao8A4gKBHO0wCObiBMgtQrClGpfNdrqXaCRJTmkYu5VxihTyFS0JIItBv1ulcLEAAg0uEgYsCqJLGQuLPbONn5hIq0ox4kjst5KJWGhsas08x3gCb99vg84LN9ey93tDlFc=,iv:eMluclcCT5AIf2CauI03Zi7CB10MC/C/eIPbFsB5+BA=,tag:LfBbjz8ttvpD3ldtaeP1TA==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - recipient: age1u5lg9qlsue2ex0wc36gvpezn3az7gpszzkxwqjega082l7uzq9fsuc7f03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiakZFMFBBNzBSSG5JNGlo
            SmZjUEVsc3I1c0Q3cU91WHQwV2JLLzg0QUh3CjJEZE14NUthN1NZUTFkK21NS1ZK
            WVJXeHRCZXhjV0FoUlp4Y3hUM05EVTQKLS0tIHdIVjdLMFBjT2pUQW5xQWxBYjlh
            TFlQc0RRaVFMR3E2citMMlZ6N1JHOGsKgJmWB10SxDm/YDvAxUiVgcu/UiqC0GeR
            MA+N0LYSOQWofTDkzFmsZYK3WM4aUF/9ewPyXjmneEa5gIDfuVLRVg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-18T18:25:11Z"
    mac: ENC[AES256_GCM,data:OtSusJ2OJAwrq2GsSqOx7JkiSaeoI49z2vfeRECtCo78SApvKc4JzB+tFsHEwnn3dES+MAKyEnvsPorxDubw2WXXLiuI2Ca4QoKNGiuh8FFb34VGGY1CgpQapPntpraQiqwpGu3fJ94BXE6m8hdjJ8JlP625GOOsiPNUIgj4IP0=,iv:qA7DA0V76HUJWYGVVEpIxMft0ichOMkNljts81JCgeQ=,tag:STVyuj75+XPEjLhonjyoJw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
