apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:JdLPW+8Noz3BjHzBbwxjanLOBvzp7DGbKQ/GcbefJOPvaz7VkEQg0exmNi2NBup7tVkaMLL3WpGzycMVlGzlUvRbe51dGc2jFGIuMnVykLG+fPuxJJ80B1XGvplksVhvmw9mQpBiYuCF5Ze1XHoB3ylzk+xlxtlOTWLv+NfopKqRpGwfkx70N+FPIlMQaCFMBfdBWvixv6IH3OOxjMQqFAeSM0RPgMC5uu/yLYwQjgp63pURP+cY4IE48j/7GQy0GBYyMIRQpCE7KTmQ++EWpbZ/cFEIinnT1uNkf0LSWxhAyM6c7KPmYkt04L8=,iv:lxZwJMS8/LEkqufmPgBuGD29j5jh+vRt25f9DQQTYMo=,tag:B8GJ6Wc4OMSaEeLGknyEGQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: tunnel-credentials
sops:
    age:
        - recipient: age1u5lg9qlsue2ex0wc36gvpezn3az7gpszzkxwqjega082l7uzq9fsuc7f03
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxOE9iT3orUkpJZEdlWFlS
            UW1rQUYrZm9DTFN1ei9qMnUrM0VXU2JaM1VVCnRnU0lEa2hsMFY1WURxaGpvaTg2
            bjhjdE5hdTZlWFZxVi96TjJZSzJLa2MKLS0tIG45d0RVSW9qNWNoWlAxS3E3aDh2
            c05PTjZkdUhrajNxRWdPRnF5bS9XTUUKc/4aB1yduyffI1mNOqN4c7uLpMOaBZQ4
            pcZkNBIoBKs0huX6dooxhkt0VyA5/2KqJNEFVw7e06fC1/inz8jqMQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-16T19:21:14Z"
    mac: ENC[AES256_GCM,data:wCHZPL2mORUQtsro7BvCLs6WbdxOLhHArWFos51OPwVvrXL/0o1lHDyjSCfUmDVioWKqwjGSm0iyMt1kjtiONMLx42vYKv1I6jeKwpOW8LXgaP5Gw66SRC3+I9JJwVmLQjBFGbTPQyj7hi58r5Jatpuv5C6m6n1Pa4AN1j6UnoI=,iv:wGvxXWBDyFd7qV5WPXJfCwCoXyiRf8pxYzFC+Du/CZ4=,tag:4bLZjwI2MdbHWgBDvNzJWg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
